---
- name: Создание пользователя и группы для Node Exporter
  user:
    name: "{{ node_exporter_user }}"
    shell: /sbin/nologin
    system: yes
    create_home: no

- name: Проверка наличия файла node_exporter на удаленной машине
  stat:
    path: "/tmp/node_exporter.tar.gz"
  register: node_exporter

- name: Копирование локального архива node_exporter.tar.gz
  copy:
    src: "node_exporter.tar.gz"
    dest: "/tmp/node_exporter.tar.gz"
    mode: '0644'
  when: not node_exporter.stat.exists
  tags:
    - copy_node_exporter

- name: Распаковка архива Node Exporter
  unarchive:
    src: "/tmp/node_exporter.tar.gz"
    dest: "/tmp/"
    remote_src: yes

- name: Копирование бинарного файла Node Exporter
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "{{ node_exporter_install_dir }}/node_exporter"
    owner: "{{ node_exporter_user }}"
    group: "{{ node_exporter_group }}"
    remote_src: yes    
    mode: '0755'

- name: Копирование systemd сервиса Node Exporter
  template:
    src: node_exporter.service.j2
    dest: "/etc/systemd/system/node_exporter.service"
    mode: '0644'

- name: Перезагрузка демона systemd
  command: systemctl daemon-reload

- name: Включение и запуск сервиса Node Exporter
  systemd:
    name: node_exporter
    enabled: yes
    state: started

- name: Обновление конфигурации Prometheus с новым хостом
  delegate_to: "{{ prometheus_server }}"
  lineinfile:
    path: "/etc/prometheus/prometheus.yml"
    insertafter: "^  - job_name: 'node_exporter'"
    line: "      - targets: ['{{ ansible_host }}:{{ node_exporter_port }}']"
  notify:
    - Reload Prometheus
