---
- name: Установка зависимостей
  apt:
    name: apt-transport-https
    state: present



- name: Проверка наличия GPG ключа на целевом сервере
  stat:
    path: "/etc/apt/trusted.gpg.d/GPG-KEY-elasticsearch"
  register: gpg


- name: Копирование GPG ключа на целевой сервер
  copy:
    src: "GPG-KEY-elasticsearch"
    dest: /etc/apt/trusted.gpg.d/GPG-KEY-elasticsearch
    owner: root
    group: root
    mode: '0644'
  when: not gpg.stat.exists  


- name: Добавление репозитория Elastic
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/7.x/apt stable main"
    state: present
    update_cache: yes

- name: Установка ElasticSearch
  apt:
    name: elasticsearch
    state: present
    update_cache: yes

- name: Запуск ElasticSearch service
  systemd:
    name: elasticsearch
    enabled: yes
    state: started


# Установка Kibana
- name: Install Kibana
  apt:
    name: kibana
    state: present
    update_cache: yes

- name: "Настройка Kibana для подключения"
  lineinfile:
    path: "/etc/kibana/kibana.yml"
    regexp: '^#server\.host: "localhost"$'
    line: 'server.host: "0.0.0.0"'

- name: Start and enable Kibana service
  systemd:
    name: kibana
    enabled: yes
    state: started